### ISSUE TITLE
Brainer Bees undoes Bumblezone's Bee wandering goal changes for its dimension

### ISSUE THREAD

**Issue by TelepathicGrunt** [CursedCauldron/Brainier-Bees#3]
I am the developer of Bumblezone and I had to make a change to the wander goal of bees. What I found was the vanilla bee wander goal is both very inefficient (can cause lag with excessive bees) and can cause bees to get stuck on the ceiling of rooms. 

I mixin into the Bee wander goal to both make it less laggy and more importantly, make the bees fly evenly through a space in midair instead of hugging the ground or getting stuck in the ceiling.
https://github.com/TelepathicGrunt/Bumblezone/blob/latest-released-Quilt/src/main/java/com/telepathicgrunt/the_bumblezone/mixin/entities/BeePathfindingMixin.java

https://github.com/TelepathicGrunt/Bumblezone/blob/bbf1566f7404707de1b9f5e9e68dd49948426a79/src/main/java/com/telepathicgrunt/the_bumblezone/entities/BeeAI.java#L11

However, Brainer Bees nukes all the bee goals and reimplements them as brains exactly with seemingly no changes. This is a problem because this is the behavior your mod has kept from vanilla bees:
![image](https://user-images.githubusercontent.com/40846040/204409882-8a4cb5ba-062e-4b3f-a70e-06945d5995c1.png)

Now this is a problem for Bumblezone while this is a picture of what I desired to do in Bumblezone's dimension (Brainer Bees is not on in pic):
![image](https://user-images.githubusercontent.com/40846040/204410364-2b48af09-9d18-41c4-bec9-a30ed78b2f68.png)

This is what Brainer Bees makes bee do again in my dimension:
![image](https://user-images.githubusercontent.com/40846040/204410555-59ec8339-488e-4166-bbbd-2db88b1dcbbc.png)

This bad for my dimension because now bees will hug the floor of the dimension until the reach a wall, then fly up the wall all the way to the ceiling and get stuck. Thus making my dimension look barebones with seemingly no bees around because they all are stuck and no longer evenly spread out through the big open space of my dimension.

Could you please add dedicated compat with my mod by calling my mod's BeeAI.smartBeesTM method if my mod is present and the bee is in my dimension? Thank you. Otherwise, I have no way of bringing back my bee wander changes and have to either mixin into Brainer Bees to add the check or mark Brainer Bees as incompatible with my mod.

**Comment by dopadream** [comment]
I'll look into it

**Comment by dopadream** [comment]
so the reason for their ai looking so similar to vanilla is because I wanted it to be as close to the real thing as possible. but trust me, it isn't the same. the bees will never forget where their home is unless it is obstructed or otherwise destroyed. this is by design. I think instead of adding dedicated compatibility for Bumblezone I'm just going to fix the issue itself, which really shouldn't be too hard
