### ISSUE TITLE
Bees in love mode crash the server when entering their hive

### ISSUE THREAD

**Issue by dopadream** [CursedCauldron/Brainier-Bees#5]
![image](https://github.com/CursedCauldron/Brainier-Bees/assets/68942129/62c323fa-f53d-4def-bb56-3c641065d611)

[crash-2023-12-29_16.50.28-server.txt](https://github.com/CursedCauldron/Brainier-Bees/files/13796735/crash-2023-12-29_16.50.28-server.txt)

don't know too much abt this one yet

**Comment by Trayshar** [comment]
I have the same issue, with a similar crash log. I just wanted to breed two bees close to each other, but instead one went into it's hive and crashed the game :(

[crash-2024-01-09_22.34.50-server.txt](https://github.com/CursedCauldron/Brainier-Bees/files/13887077/crash-2024-01-09_22.34.50-server.txt)

**Comment by dopadream** [comment]
Fixed
