### ISSUE TITLE
server crash pollitation step or smth idk

### ISSUE THREAD

**Issue by Lumenyl-Cal** [CursedCauldron/Brainier-Bees#6]
server crash pollitation step
[crash-2024-01-28_02.19.49-server.txt](https://github.com/CursedCauldron/Brainier-Bees/files/14116740/crash-2024-01-28_02.19.49-server.txt)

**Comment by dopadream** [comment]
I fixed this like 3 days ago. Update to 1.4.3 of Brainier Bees

**Comment by Lumenyl-Cal** [comment]
very cool
