### ISSUE TITLE
crash with breeding bees entering hive?

### ISSUE THREAD

**Issue by diegoadobo** [CursedCauldron/Brainier-Bees#7]
I was breeding some bees and one of them was pollinated and I clicked on it with a poppy and then the server died :) Looking at the closed issues on here I can assume it probably entered its hive since I was right next to one. I'm on 1.20.4 using the mod version 1.4.3. Afraid the crash may have not been resolved...

[crash-2024-05-11_03.16.21-server.txt](https://github.com/CursedCauldron/Brainier-Bees/files/15283355/crash-2024-05-11_03.16.21-server.txt)

**Comment by dopadream** [comment]
Unable to reproduce on 1.6, do let me know if the problem persists
